### ISSUE TITLE
Revisiting issue with now playing dispaly

### ISSUE THREAD

**Issue by Pastim** [medoc92/upplay#12]
I know I raised this before, but is there any way you could provide an option to not read the 'Now Playing' back from the renderer?  The text display I get is mangled by my renderer for non basic Ascii, and the track quality (the *s) are wrong.  It's only a niggle for me, but rather persistent :)

**Comment by medoc92** [comment]
Hi,

I know we talked about this before, but can't find it. So a few questions:

Is this an OpenHome or an UPnP renderer ?

Are you sure that the renderer is mangling the data and not upplay ? Does it do the same thing with another CP ?

**Comment by Pastim** [comment]
You asked me to do a trace and I think I did, and it seemed it was my UPnP renderer (Musical Fidelity M1CLiC) that was at fault.  

BubbleUPnP was OK, although to be honest I hardly use it, and when I just tried it I could not get it to function at all.  The wonders of IT....

**Comment by Pastim** [comment]
I just found the previous note - It was Issue 8.

**Comment by medoc92** [comment]
Thanks. I pushed an update which should result in always displaying local data instead of what the renderer sends (as long as we do have the data: does not work if the track was added by another CP of course). If it fixes your display issue, I may make it optional or keep it as default. Please try it when you have a moment.

**Comment by Pastim** [comment]
Wonderful!  That does just what I hoped. Thanks very much indeed.

**Comment by medoc92** [comment]
Great ! So I'll just keep it for the moment. If we discover issues with this approach, I'll make it switchable.
