### ISSUE TITLE
Suggestion to improve volume adjusment

### ISSUE THREAD

**Issue by mihaipora** [medoc92/upplay#14]
Right now if I want to change the volume I take the slider, drag & drop to the new level and the change is sudden. If the volume is too high or too low, I need to do it again . Lucky me I know binary search so it's log(n) :)

The suggestion is to update the volume while the user is moving the slider. Maybe updating it every 0.5 or 0.2 seconds while sliding the control will provide better feedback.
I imagine that moving the slider slowly and waiting 0.2 seconds to hear the difference is better than moving it blindly and then moving it again. Especially with trackpad instead of mouse, it makes a difference in usability.

**Comment by medoc92** [comment]
I agree, this ennoys me too, it's probably time to do something about it
