### ISSUE TITLE
Remove underline from list

### ISSUE THREAD

**Issue by rfritzzz** [medoc92/upplay#17]
A very small thing...
I think the underline (like hyperlinks) can be removed from the list view items (albums etc.). It is obvious that the elements can be selected.

PS: Thanks for the great application!

**Comment by medoc92** [comment]
Agreed, this will be in the next release. Actually what I'd also need to add is a way for the users to use their own style sheet. For the moment, you can get rid of the underlines by editing /usr/share/upplay/cdbrowser/cdbrowser.css and adding the following lines:

````
a {
    text-decoration: none;
}
````
