### ISSUE TITLE
Click on list item while loading doesn't work sometimes

### ISSUE THREAD

**Issue by rfritzzz** [medoc92/upplay#20]
With bigger collections loading the browse list takes a little longer but the list is updated frequently, fine. When you click on an entry while the list is still loading, sometimes it happens that the breadcrumb menu shows the clicked item path but the list is not one (folder) depth deeper.

**Comment by medoc92** [comment]
I think that I fixed it (last commit), but I'm not 100% sure, because it was not always obvious to reproduce.
