### ISSUE TITLE
Feature Suggestion: local renderer

### ISSUE THREAD

**Issue by jurgynet** [medoc92/upplay#21]
I would like having the option of an embedded local renderer. That would expand the use cases and user base of upplay.

**Comment by medoc92** [comment]
I can see the point, but it would add a big amount of complexity, and there are already so many local players ! (Some of which have the ability to access UPnP servers if I'm not making up stuff in my dreams). So, no, I won't do it, upplay is not meant to be another general-purpose player, but just a lightweight UPNP audio control point. You can just install upmpdcli/MPD if you want to play locally from upplay.

**Comment by jurgynet** [comment]
mostly thinking about the windows version of upplay... and want a localhost only dlna renderer. Know of anything like that?

**Comment by medoc92** [comment]
Jriver ?


Le 14 octobre 2015 21:53:04 GMT+02:00, Alan Jurgensen <notifications@github.com> a écrit :
>mostly thinking about the windows version of upplay... and want a
>localhost only dlna renderer. Know of anything like that?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/medoc92/upplay/issues/21#issuecomment-148177184

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Pastim** [comment]
foobar2000 with the upnp plugin giving a local renderer?
