### ISSUE TITLE
Feature Suggestion: Choose where Library pane is anchored

### ISSUE THREAD

**Issue by jurgynet** [medoc92/upplay#22]
Would be nice to have Library on the left, or on the bottom... or on the right.
Instead of only the right...  
Maybe View, Library now has a submenu: right,left,bottom.  
Or set anchor of library on prefs page.
Thanks!

**Comment by medoc92** [comment]
I'm not against the idea, but I think that the Sayonara code I started from does not make that easy (the "Player" part is not another pane, but actually part of the main window). Still, I'll take a look when I have a moment (mostly busy with other stuff right now).

**Comment by medoc92** [comment]
Indeed, this would be complicated.
