### ISSUE TITLE
Windows version cannot find media renderers due to network interface

### ISSUE THREAD

**Issue by Koenvh1** [medoc92/upplay#26]
Whenever I start up Upplay, it cannot find any media renderers. I think this is due to the way Upplay selects the network interface to run on, because after I disabled USB tethering on my phone, it showed my local renderer (foobar2000 with UPnP plugin). Please make an option to select the network interface.

**Comment by medoc92** [comment]
Hi,

I'm not ignoring this issue, just busy. Will come to it :)

**Comment by Koenvh1** [comment]
Well, it is great that you made this program in the first place. It is the first UPnP player I've found for Windows that is easy enough that I don't need to explain how it works, and supports audio + video + images. This is the only problem I have come across so far. :-)

**Comment by medoc92** [comment]
I added code to allow selecting an interface (from View->Preferences). It seems to work, but of course it has had little testing. The setup file is here: http://www.lesbonscomptes.com/upplay/downloads/windows/upplaysetup-1.3.0-w1.exe

Please try it when you have a moment, and let me know if it works for you.

**Comment by Koenvh1** [comment]
Thank you, this works. The problem probably was that it defaulted to the top adapter, which is a VMWare loopback adapter. 

Still, great work! And now it is even better :+1:
