### ISSUE TITLE
Control chromecast-audio

### ISSUE THREAD

**Issue by frogmaster** [medoc92/upplay#27]
using upplay 1.2.1 and libupnpp 0.13.0

UPPLAY_LOGLEVEL=6 upplay 2>
output:
[trace.txt](https://github.com/medoc92/upplay/files/75548/trace.txt)

**Comment by medoc92** [comment]
Hi,

Somebody else reported not seeing the chromecast devices with upplay, so there is quite definitely a bug. 

I don't have the device around, so it would be very useful if you could dump and attach the device description files (you can do this with upnp-inspector for example, right-click the device and choose "extract device and service descriptions). 

Hopefully I'll see something in the desc files.  

Else I guess that I'll have a good reason to buy one :)

**Comment by frogmaster** [comment]
Managed to get upnp-inspector to work somehow, but it fails to find the dongle.  I downloaded the device_desc.xml file though, hope it helps.

```
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <URLBase>http://192.168.1.142:8008</URLBase>
  <device>
    <deviceType>urn:dial-multiscreen-org:device:dial:1</deviceType>
    <friendlyName>Krooks</friendlyName>
    <manufacturer>Google Inc.</manufacturer>
    <modelName>Chromecast Audio</modelName>
    <UDN>uuid:1b5d45ec-322d-e7fa-97df-85b9cb85fb35</UDN>
    <iconList>
      <icon>
        <mimetype>image/png</mimetype>
        <width>98</width>
        <height>55</height>
        <depth>32</depth>
        <url>/setup/icon.png</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
        <serviceType>urn:dial-multiscreen-org:service:dial:1</serviceType>
        <serviceId>urn:dial-multiscreen-org:serviceId:dial</serviceId>
        <controlURL>/ssdp/notfound</controlURL>
        <eventSubURL>/ssdp/notfound</eventSubURL>
        <SCPDURL>http://www.google.com/cast</SCPDURL>
      </service>
    </serviceList>
  </device>
</root>
```

**Comment by Pastim** [comment]
Please forgive my ignorance, but since when did upplay support Chromecast?  I must have missed something.  I have a Chromecast video version 2.  My other music server (LMS) is also having chromecast support added, but it's not the same as upnp, and this seems to support both video and audio versions.

I'm on 1.2.1.

**Comment by medoc92** [comment]
Upplay does not support chromecast at the moment. We were wondering, but as far as I can see from the description document, this is not an UPnP Media Renderer at all, so no wonder upplay does not list it.

So I think that's it then, and we can close this ?

**Comment by frogmaster** [comment]
Guess so. I thought it was upnp renderer But yeah, seems that puseaudio-dlna has different plugin for chromecast also...
