### ISSUE TITLE
Huge delay between tracks

### ISSUE THREAD

**Issue by gueygel** [medoc92/upplay#28]
When a track ends, upplay takes up to 9 minutes to play the next track in the playlist. If I double click it, it starts instantly.
I've also observed that, sometimes, when the next track starts playing, upplay still shows as if the one sounding were the previous one. Then, when it ends, it repeats the same track but this time upplay shows the correct one. 
I wonder whether these issues are related. I encountered a similar syncing problem using an old version of BubbleUPNP on my phone (a control point app for Android), but eventually it got fixed.

I'm using Ubuntu 15.04 + rygel as media server, upplay installed on the same system, and a pair of DLNA-enabled speakers (KEF X300A Wireless).

Above all, thanks a lot for the good work! I've been looking for something like this on linux for a long time, besides the rudimentary gupnp...

**Comment by DoomHammer** [comment]
Might be related to poorly implemented MediaRenderer. I was having similar issues when testing my Renderer before it got properly implemented ;)

**Comment by gueygel** [comment]
Hmm, woudn't the MediaRenderer be upplay in this case? Or is it upplay +  some other part of my system? (Excuse my ignorance of UPnP jargon...)

**Comment by medoc92** [comment]
Hi,

This is probably some incompatibility between upplay and the KEF renderer. To investigate, it would be useful to enable the libupnp log file and run upplay. You can do it by starting it in the following way on the command line:

     UPPLAY_UPNPLOGFILENAME=/tmp/somefile UPPLAY_UPNPLOGLEVEL=6 upplay

Then you need a way to mark the point in the log file where things stop (then start). Given the delay, you should have enough time to just read the file in an editor and get the current end line number. Then attach the trace, or, if it's too big we'll find another way, and tell me the line number where it stopped. Hopefully I'll be able to see what's happening.

The strange thing actually is why it starts again at all after all this time !

It would also be useful if you could cut/paste a number of console (upplay output) lines before and after the gap, to complement the lib output.

**Comment by gueygel** [comment]
Hi, thanks a lot for your prompt reply!

I wasn't able to do the testing until now. Actually, this time the next track didn't start at all... Upplay interface was marking the second track in play mode but the slider was stuck at 00:00 for more than 20 minutes. Then I just quit the program.

I attach the upplay console output starting from when the first track ends.
The log file is pretty big. The same moment occurs around line 53777.

[upplay_console_output.txt](https://github.com/medoc92/upplay/files/84129/upplay_console_output.txt)
[upplay_log.txt](https://github.com/medoc92/upplay/files/84127/upplay_log.txt)

Hope this helps!

**Comment by medoc92** [comment]
Hi,

As far as I can see in the log, the Renderer accepts the "nextAvTransportURI" command for transitionning to the next track, and then just does nothing (does not even signal that it's stopped).

I'd suggest checking for a firmware upgrade.

Also, it would be interesting to try with another "known good" controller, like Bubble UPNP from Android for example, there is a free version.

Oops, actually same problem with Bubble:
http://forum.xda-developers.com/showpost.php?s=a33e7fbec2b47fbb394b36c4e12310b9&p=59533928&postcount=8858

So the firmware update appears to be the main hope.

**Comment by gueygel** [comment]
OK, although I'm not very optimistic about waiting for firmware updates, I'll try and contact KEF about it.

Now that I remember, they have their own Android control point app, "KEF DMC App". Never used it because Bubble seemed much more polished but I'll give it a go.

Thanks for your help!

**Comment by medoc92** [comment]
Did you actually try with Bubble ? The other guy seemed to have some success at least with mp3 files.

**Comment by gueygel** [comment]
I did use Bubble for a while and wasn't having this issue (as I mentioned in the first post), but it failed the other day when I was trying upplay in the same manner. I didn't check whether the files I used for testing were flac or mp3 though... Will try again.

**Comment by medoc92** [comment]
Sorry, I had not noted that Bubble ended up working last time (bad memory + several things at the same time -> should reread from start each time...)

Raspberry PI + Hifi-Berry + alim/box < 100 $ ----> aux input

 :)

**Comment by gueygel** [comment]
No worries mate ;)
Yeah I've thought about the PI more than once... I haven't given up yet because it's so frustrating to have DLNA-enabled speakers that can't function wirelessly!

**Comment by medoc92** [comment]
Nothing  I can do at this point I'm afraid...
