### ISSUE TITLE
AlbumArt not shown when switching back to SourceType Playlist

### ISSUE THREAD

**Issue by Floo** [medoc92/upplay#33]
I guess there is a small bug when showing the album art. If I am in Playlist mode, add new items to a playlist and play them everything workls fine. However, if I then change the SourceType to Radio, play radio and switch back to SourceType Playlist, I can play songs from the playlist but the album art is not shown. As far as I can see, the file albumArtURI in MetaData remains empty.

Floo

**Comment by medoc92** [comment]
Hi, 

This was an upmpdcli issue, I just pushed a change which should hopefully fix it.
