### ISSUE TITLE
Notification Support

### ISSUE THREAD

**Issue by v00d00** [medoc92/upplay#34]
Hi,

I was thinking of implementing notification support.

Would be it OK to use libnotify directly? Or does it need to be cross platform?

Also, thanks for the app, its awesome.

**Comment by medoc92** [comment]
Hi, 

This is a great idea, but upplay needs to build under Windows, so some kind of encapsulation is definitely  in order (it is not necessary that notifications will work under Windows, but the software must build)

**Comment by v00d00** [comment]
Thanks for letting me know, I will use https://github.com/KDE/snorenotify.

**Comment by medoc92** [comment]
This looks nice, but it's not packaged at least by Ubuntu , so please make sure that everything is conditionally included, I'm not sure that either you and me wants to package this lib ( I don't :) )

To be frank, I think that the right approach would be to execute an external command: it's not like state changes that often, and this would make it fully dynamic: the command is either present or not at run time, no build-time issues.

**Comment by medoc92** [comment]
closed by https://github.com/medoc92/upplay/commit/bd5e49a11b900935279304ced0d7b00623de9e3c
