### ISSUE TITLE
upplay on Dell XPS12/Windows 10 does not find media renderers or source

### ISSUE THREAD

**Issue by lozdown** [medoc92/upplay#35]
I have upplay running on lubuntu which works perfectly. It finds my 3 renderers (raspberry pi/volumio*2 lubuntu/mpd + upmpdcli *1) and media server (raspberry pi/volumio + minimserver). The same version upplay(1.2.0) installed on Dell XPS12/Windows 10 does not locate any renderers or media server. The Dell XPS12 only has wireless network connection connected to the same internal network.

Linn Kinsky does work correctly after selecting the wireless network during its initial configuration.

**Comment by medoc92** [comment]
I think that upplay 1.2.3 is the first version with an option to select network interfaces. 1.2.4 is the current version, maybe try to install it and see if selecting an interface improves the issue ?
http://www.lesbonscomptes.com/upplay/upplay-windows.html

**Comment by lozdown** [comment]
upplay 1.2.4 works fine
