### ISSUE TITLE
PLease add feature to play local music

### ISSUE THREAD

**Issue by 3x3ption** [medoc92/upplay#37]
Hi

can you implement a function to play local mp3's oder other local music formats?

that would be wonderful =)

**Comment by medoc92** [comment]
Sorry, but I think that I am not going to do this: there are myriad other much more complete players which can do this, and I'd rather keep upplay simple. 

If you really want to play local files, why not run a local minidlna + upmpdcli/mpd ?

**Comment by 3x3ption** [comment]
Ok thanks
