### ISSUE TITLE
upplay 1.2.4 loses windows controls on lubuntu 16.4

### ISSUE THREAD

**Issue by lozdown** [medoc92/upplay#40]
upplay 1.2.4 running on lubuntu 16.4 displays and works but the main window does not show window control bar (i.e. that holds the window close, resize, minimise buttons).

**Comment by Pastim** [comment]
Try changing the menu settings under 'Settings, Appearance', the Behaviour tab.   I have menus 'always displayed' and 'in the title bar'.  I had problems with other applications before doing this.

**Comment by lozdown** [comment]
I can't find that setting under lubuntu or under Ubuntu - please would you elaborate. 
Thanks

**Comment by Pastim** [comment]
I'm on Ubuntu 16.04.  If I go to 'Settings', and 'Appearance' there are 2 tabs, 'Look' and 'Behaviour'.  Under 'Behaviour' there are various Menu settings, including the two I mentioned.

If you are on lubuntu, and/or 16.40, it may be different.
