### ISSUE TITLE
No scrolling in Songcast Tool dialog

### ISSUE THREAD

**Issue by kylegordon** [medoc92/upplay#43]
Hi,

When opening the Songcast Tool, if you have multiple sources and senders, there is no way to scroll down the list. If you have too many, the window grows too long for the screen, and the window has to be moved up with alt+click+drag repeatedly to get to the bottom.

Admittedly this is unlikely to be a common problem, but thought it was worth mentioning :-)

Kyle

**Comment by medoc92** [comment]
I makes sense that this may become an issue on smaller screens, I have a tendancy to forget that not all displays are HD.  I'd need to give it a try at 1024x768 from time to time. 

How would you think this should be handled ? It would seem that separately scrolling the senders and receivers and keeping the dialog button fixed would make the most sense ?

I'm not sure that this is not beyond my qt abilities, but I can give it a try.

**Comment by kylegordon** [comment]
Yeah, I think two scrolling windows would be ideal - one for senders, one for receivers. 

Happy to help with testing :-)

**Comment by medoc92** [comment]
The new current code has scrolling in the songcast window, if you want to give it a try...

**Comment by kylegordon** [comment]
Yes, that looks great. Much easier to find components when you have many of them! Thank you
