### ISSUE TITLE
Album & Track Display has gone

### ISSUE THREAD

**Issue by JazzDoc** [medoc92/upplay#44]
Upplay was working fine yesterday. When I ran it this morning, playback is fine although I have lost the album cover artwork image in the top left hand corner, the name of the album and track playing and the functionality of the track progress bar showing time elapsed and allowed me to move to a different part of the track. I use JRiver Media Center as a DLNA media server and JPLAYStreamer. I have checked the JRiver Media Center and JPLAY settings and nothing has changed from yesterday. I also tried uninstalling and reinstalling Upplay without success. I have selected 'Microsoft Hosted Network Virtual Adapter' as Network interface in UPPlay's Preferences as other users have reported that this option offers better sound quality. Can you please suggest how to solve the problem with missing display. Thank you

**Comment by medoc92** [comment]
JazzDoc writes:
 > Upplay was working fine yesterday. When I ran it this morning, playback is fine
 > although I have lost the album cover artwork image in the top left hand corner,
 > the name of the album and track playing and the functionality of the track
 > progress bar showing time elapsed and allowed me to move to a different part of
 > the track. I use JRiver Media Center as a DLNA media server and JPLAYStreamer.
 > I have checked the JRiver Media Center and JPLAY settings and nothing has
 > changed from yesterday. I also tried uninstalling and reinstalling Upplay
 > without success. I have selected 'Microsoft Hosted Network Virtual Adapter' as
 > Network interface in UPPlay's Preferences as other users have reported that
 > this option offers better sound quality. Can you please suggest how to solve
 > the problem with missing display. Thank you
 > 

I'm sorry, I have no idea of what may be happening here, and I can't test
because I have neither JRiver nor upplay.
