### ISSUE TITLE
compile error when builing latest version

### ISSUE THREAD

**Issue by humarf** [medoc92/upplay#45]
Hi,

sorry, seems to be not my day. Now receiving an error when updating upplay as well. Could you please check?

`g++ -Wl,-O1 -o upplay .obj/mainw.o .obj/mw_connections.o .obj/mw_controls.o .obj/mw_cover.o .obj/mw_menubar.o .obj/trayicon.o .obj/mdatawidget.o .obj/playctlwidget.o .obj/playerwidget.o .obj/GUI_Playlist.o .obj/PlaylistItemDelegate.o .obj/GUI_PlaylistEntryBig.o .obj/GUI_PlaylistEntrySmall.o .obj/PlaylistItemModel.o .obj/ContextMenu.o .obj/PlaylistView.o .obj/confgui.o .obj/prefs.o .obj/sortprefs.o .obj/progresswidget.o .obj/songcastdlg.o .obj/soundslider.o .obj/volumewidget.o .obj/directslider.o .obj/CSettingsStorage.o .obj/Helper.o .obj/Style.o .obj/application.o .obj/cdbrowser.o .obj/dirbrowser.o .obj/randplayer.o .obj/rreaper.o .obj/audioscrobbler.o .obj/notifications.o .obj/playlist.o .obj/playlistavt.o .obj/playlistlocrd.o .obj/playlistohpl.o .obj/playlistohrd.o .obj/songcast.o .obj/upputils.o .obj/upplay.o .obj/ohpool.o .obj/moc_mainw.o .obj/moc_trayicon.o .obj/moc_mdatawidget.o .obj/moc_mdatawidgetif.o .obj/moc_playctlwidget.o .obj/moc_playctlwidgetif.o .obj/moc_playerhwidget.o .obj/moc_playervwidget.o .obj/moc_GUI_Playlist.o .obj/moc_GUI_PlaylistEntry.o .obj/moc_GUI_PlaylistEntryBig.o .obj/moc_GUI_PlaylistEntrySmall.o .obj/moc_PlaylistItemModel.o .obj/moc_ContextMenu.o .obj/moc_PlaylistView.o .obj/moc_confgui.o .obj/moc_prefs.o .obj/moc_sortprefs.o .obj/moc_progresswidget.o .obj/moc_progresswidgetif.o .obj/moc_renderchoose.o .obj/moc_songcastdlg.o .obj/moc_sourcechoose.o .obj/moc_soundslider.o .obj/moc_volumewidget.o .obj/moc_volumewidgetif.o .obj/moc_directslider.o .obj/moc_CSettingsStorage.o .obj/moc_application.o .obj/moc_cdbrowser.o .obj/moc_dirbrowser.o .obj/moc_randplayer.o .obj/moc_rreaper.o .obj/moc_audioscrobbler.o .obj/moc_notifications.o .obj/moc_playlist.o .obj/moc_playlistavt.o .obj/moc_playlistlocrd.o .obj/moc_playlistnull.o .obj/moc_playlistohpl.o .obj/moc_playlistohrcv.o .obj/moc_playlistohrd.o .obj/moc_avtadapt.o .obj/moc_ohifadapt.o .obj/moc_ohpladapt.o .obj/moc_ohrdadapt.o .obj/moc_songcast.o .obj/moc_avtransport_qo.o .obj/moc_cdirectory_qo.o .obj/moc_ohinfo_qo.o .obj/moc_ohplaylist_qo.o .obj/moc_ohproduct_qo.o .obj/moc_ohradio_qo.o .obj/moc_ohreceiver_qo.o .obj/moc_ohtime_qo.o .obj/moc_ohvolume_qo.o .obj/moc_renderingcontrol_qo.o .obj/qrc_upplay.o    -L/usr/lib64/qt4 -lupnpp -lQtWebKit -lQtScript -L/usr/lib64/qt4 -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
.obj/cdbrowser.o: In function `CDBrowser::search(std::string const&, std::string const&, QPoint)':
cdbrowser.cpp:(.text+0x236c): undefined reference to `Logger::getTheLog(std::string const&)'
cdbrowser.cpp:(.text+0x23ad): undefined reference to `Logger::getTheLog(std::string const&)'
cdbrowser.cpp:(.text+0x23fa): undefined reference to `Logger::getTheLog(std::string const&)'
.obj/cdbrowser.o: In function `CDBrowser::simpleAdd(QAction*)':
cdbrowser.cpp:(.text+0x27a6): undefined reference to `Logger::getTheLog(std::string const&)'
cdbrowser.cpp:(.text+0x27e6): undefined reference to `Logger::getTheLog(std::string const&)'
.obj/cdbrowser.o:cdbrowser.cpp:(.text+0x2860): more undefined references to `Logger::getTheLog(std::string const&)' follow
collect2: error: ld returned 1 exit status
Makefile:302: recipe for target 'upplay' failed
make: *** [upplay] Error 1`

Thanks a lot and best regards
humarf

**Comment by medoc92** [comment]
You seem to be linking with -L/usr/lib64, but at the previous step you installed to /usr/local/lib ? Maybe there is an old copy of libupnpp in /usr/lib64 ?

I'm not sure how to pass an LD search path to qmake, I never use it. Maybe the simplest approach would be to just edit the LIBS line in the generated Makefile...

**Comment by humarf** [comment]
Sorry, my fault. I changed prefix directory.

Best regards
humarf
