### ISSUE TITLE
Feature Suggestion: volume (+) (-) buttons

### ISSUE THREAD

**Issue by artmg** [medoc92/upplay#46]
Using a mouse on the volume slider can cause rather large jumps in volume. This risks accidentally knocking the levels too high for people in the room, or even for the speakers.

It would be great if there were a way to adjust the volume in steps up or steps down. Perhaps the simplest implementation might be keypresses of the + plus and - minus keys, however in the longer run if you have time to review the UI, there could also be clickable buttons on the graphical interface.

**Comment by medoc92** [comment]
After checking the code, in the current released version, you can use alt+up alt+down to adjust the volume. You are supposed to be able to use alt+left/right to seek but this does not work well.

I changed the code to fix the seeking and use bare Up/Down/Left/Right as alt is best left to the window manager. So no +- for now, but I guess that Up/Down are fine too. Or the mouse wheel.

**Comment by medoc92** [comment]
Oops, Up and Down are useful to navigate the playlist. So it will be either Ctl+Up, Ctl+Down, Plus, Minus for the volume...
