### ISSUE TITLE
Upplay can't find my Media Renderer

### ISSUE THREAD

**Issue by PeterCodar** [medoc92/upplay#47]
I know for sure that my device is up and running (it will be found with other software).

Do I have a possibility to let Upplay know the IP-address of my Media Renderer?
How can I make the Media Renderer be known to Upplay?

OS: Windows 10
Device: UPnP device connected by WLAN (working with other software)

**Comment by medoc92** [comment]
I do know that there is a problem in my discovery code, I've been searching for it for a long time. The usual symptom is that devices are sometimes not found, but they usually "come back" by restarting upplay. 

If this does not work for you, then this is another issue. Maybe there is an incompatibility (upplay bug) with your device. What kind of renderer is it ? 

You can't tell the device IP to upplay, UPnP just does not work this way.

**Comment by medoc92** [comment]
No feedback
