### ISSUE TITLE
feature request: option to turn off gapless playback

### ISSUE THREAD

**Issue by Singlewordedpoem** [medoc92/upplay#48]
My renderer seems to have a problem with the upnp gapless playback commands; in the Bubbleupnp app there's an option to turn this on or off, and when I turned it on, track advancement stopped working properly. Upplay seems to use gapless playback by default, and there's no option to turn it off (that I know of), and I get the same problems with the renderer as when I turned gapless playback on in Bubbleupnp.

**Comment by medoc92** [comment]
Thanks for the suggestion, this is now in the source, and will appear in a future release.
