### ISSUE TITLE
Server directory name broken in UTF-8

### ISSUE THREAD

**Issue by parkmino** [medoc92/upplay#51]
'(servers) > ... > Korean directory' characters are broken while english is fine.
It might be related to the used font.

**Comment by medoc92** [comment]
As you mention, I think that this is a font issue (I can display european accented chars without problem, so I think that the Unicode processing is ok.

You can change the font at the top of /usr/share/upplay/cdbrowser/cdbrowser.css:

````
/* General font selection. This is the place to adjust the font size for the
 * directory browser area. The distributed file uses the system
 * default (the size spec is commented out. */
html, body, form, fieldset, table, tr, td, img {
    font-family:Arial,helvetica,sans-serif;
/*    font-size: 10pt;*/
}
````

**Comment by parkmino** [comment]
I changed the font, however, the browse path is still broken.

**Comment by tack1953** [comment]
I have the same issue in Japanese UITF-8, I confirmed Garbled characters bug in upplay1.2.7(debian GNU/Linux).
Characters of contents displayed correctly, but directory name including Japanese UTF-8 would be Garbled characters. I swtched back to upplay 1.2.6, in 1.2.6 displayed correctly.
