### ISSUE TITLE
[Enhancement] Better Qt5 UI consulting Madrigal

### ISSUE THREAD

**Issue by parkmino** [medoc92/upplay#52]
FYI, the author of Cantata is developing Qt5 Openhome Control Point.
I think you can borrow some UI codes from this.
I prefer Upplay generally, Madrigal is in it's early stage and supports only openhome server at the moment.

https://github.com/CDrummond/madrigal

**Comment by medoc92** [comment]
Thanks for the pointer, I'm glad another CP is coming. I hate GUI development, so the sooner I can drop upplay, the better...
