### ISSUE TITLE
 Feature Suggestion: Is it possible to support single track repeat?

### ISSUE THREAD

**Issue by tack1953** [medoc92/upplay#54]
Hello,
As far as I know, most of the upnp control point doesn't support single track repeat fanction including Linn Kazoo, upplay and so on.
BubbleuPnP for Android does support repeat one track on rygel renderer, but in the case of my Esoteric N-05(OpenHome compliant), it doesn't (only support entire playlist repeat function).
I suspect that OpenHome compliant devices don't support single track repeat.
If it is possible to support single track repeat on upplay, I would like it.
Anyway, Thank you for the elaboration.
By the way. is there any way to donate you?
I often use upplay so, I hope I can be of any help to you.

**Comment by medoc92** [comment]
Hi,
As far as I remember, UPnP does not support single track repeat at all. The only approach I can think of would be to use a playlist with a single track and use repeat on this. 

Would this be a problem ?

Trying to emulate single-track repeat from the control point on an openhome renderer is not going to work well (the renderer will begin playing the next track before the cp can tell it to switch back to the repeated one). On a non-openhome renderer, it would be feasible which is probably why Bubble supports it there.

But, again, the simplest approach would be a single-track playlist, so that the function which is probably lacking in upplay is actually 'remove all tracks except this one'.

**Comment by tack1953** [comment]
Thank you for youre reply.
I'm sorry to hear that it is openhome specification.
I'll use playlist with single track.

>But, again, the simplest approach would be a single-track playlist, so that the function which is >probably lacking in upplay is actually 'remove all tracks except this one'.

If it is easy to support, I'd like it.
Thank you anyway.

**Comment by tack1953** [comment]
I did further invenstigation on BubbleuPnP & DLNA renderer Rygel.
By default, Rygel DLNA renderer enables single track repeat,so I checked "Enable gapless control" in
uPnP Tweaks. then, Single track repeat didn't function properly any more(When tune ended, moved to next track). Judging form this case, I assume there is a connection between gapless control and single track repeat. It is mere guess, but LINN probably disabled single track repeat function and enabled gapless control when they developed OpenHome compliance . Most of DLNA only  devices can't enable gapless control but have single track repeat function.
Unfortunately, I am not a programmer so I can't modify upplay or other uPnP CP, but I wonder if it is possible to implement single track repeat by disabling gap less control.

**Comment by tack1953** [comment]
I tested UpMpd with Bubbleupnp and mpdclient Cantata.
UpMpd is openHome compliant software renderer, so I couldn't use repeat track feature on bubbleupnp. but cantata has single repeat mode, with this feature single track repeat worked fine.
maybe it is not impossible to implement single track repeat in uPnP CP.
UpMpd and Upplay are nice softwares. Thank you for wrting these softwares.

**Comment by medoc92** [comment]
Actually it's quite simple to understand what happens with gapless and single track repeat.

When doing gapless, the renderer knows the track it's going to play after the current one. This is is true with OpenHome (where it has the whole playlist), and with UPnP AV (where it just knows the next track).

When it comes at the end of the current track, the renderer just goes through to the next one, which means that the control point can't tell it to repeat the current track instead. It could do it anyway, but after the second track has began playing, which would not be nice.

There is nothing you can do about this when using openhome (other than using a single track playlist). So, no single-track within playlist with OpenHome, ever.

When using UPnP AV, the control point just has to avoid setting up the next track, and tell the renderer to replay when it comes at the end of the current one. So, single-track repeat is always possible with UPnP AV, the control point just has to implement it.

The issue with single track repeat not working with gapless playback looks like a bubbleupnp bug. Bubble should remember not to set the next track when it is in single track repeat mode. There is a goo chance that, if you report this to Bubble, they'll fix it.

You can disable OpenHome support in upmpdcli by setting openhome=0 in /etc/upmpdcli.conf, it will then behave as a pure UPnP AV renderer, and should do single-track repeat with bubble (if you disable gapless in bubble, for now).

**Comment by tack1953** [comment]
I'm sorry for my ignorance of openhome and UPnP AV.
Now I understood how upmpdcli behave by options.
I'll get back on track. according to upplay(select source) ,my Esoteric N-05 support not only OpenHome
but also UPnP AV. However, I can't make any playlist when select source to UPnP AV. Even if I could use UPnP AV mode, current Upplay doesn't support single track repeat mode.
Maybe I should use OpenHome mode with one track playlist, I'd appreciate if you would implement
single track mode. Upplay + UpMpd + Cantata(repeat+single track mode) works fine, but I've bought Network Player:-)(I use N-05 as main renderer so I usually don't use UpMpd, a shame)

**Comment by tack1953** [comment]
Hi,
I confirmed UpMpd can repeat single track on BubbleuPnP when modify upmpdcli.conf(Openhome=0).
I'd appreciate if single track repeat of upnp AV device is available on Upplay.
Thank you for telling me the detailed information.

**Comment by tack1953** [comment]
Sorry for many posts,
but I don't understand  Why Upplay + UpMpd(Openhome=1) + Cantata(repeat+single track mode) works fine(the instant I enebled repeat ALL function of Upplay, Cantata's repeat function was enabled) Judging from this case, I assume even a OpenHome renderer can repeat single track depending on the software implementation.

**Comment by medoc92** [comment]
Cantata is an mpd client. mpd has single-track repeat (I think), but you just can't set it through upnp.

**Comment by tack1953** [comment]
I hit on an idea of creating upplay's own playlist in addition to OpenHome's OnDevicePlaylist.
MY idea is When Upplay play songs, send a single song data from upplay's own playlist to OnDevicePlaylist one by one, not the whole playlist. In this case, it is easy to choose single track from the Whole playlist and let upplay repeat single track. Actually, This idea is borrowed from how BubbleuPnP behaves when the renderer is DLNA(uPnP AV)compliant (not OpenHome Compliant). BubbleuPnP seems to have its own playlist to enable support for many DLNA only renderer, since many of the DNLA only renderer doesn't support OnDevicePlaylist. My idea is a bit diffrent in that it let OpenHome renderer use two playlists to avoid the limitation of OpenHome renderer.
But  is it worth spending such many time and efforts? Since there is a workaround of making a single track playlist. If I do say so myself:-(
regards

**Comment by medoc92** [comment]
Yes, I think that the last idea is too complicated. I just added an entry to the playlist context menu to invert the current selection. So you can reduce the playlist to a single track by clicking it, inverting the selection and clicking remove.  I think that it's a bit more of general purpose than just 'select 1 track', because you could select a few tracks this way, but there is one more click, which we'll have to live with...
