### ISSUE TITLE
Feature suggestion: support for internet radio

### ISSUE THREAD

**Issue by Singlewordedpoem** [medoc92/upplay#58]
As far as I'm aware it is not currently possible to make the renderer play internet radio streams. I recently found an Android app that enables this, called "hqradio", website: [http://hqradio.net/index.html](http://hqradio.net/index.html). It would be amazing if this also becomes possible from my linux desktop :)

**Comment by medoc92** [comment]
Hi,
This function does not depend on the control point. Most renderers probably have the capability to play internet radio streams, provided with the URL. Dealing with radio URLs can be implemented by the Renderer itself (e.g. upmpdcli has a radio function), or by the Media Server. You need to look at the doc, or search google, for your renderer and/or media server radio stream capabilities.
