### ISSUE TITLE
[Feature Request] Option to sort by tracknumber per default

### ISSUE THREAD

**Issue by cars10** [medoc92/upplay#59]
[Feature Request] Option to sort by tracknumber per default

Would be awesome =)

**Comment by medoc92** [comment]
I assume that this is for the playlist ?

This could easily be done, but, in order to do the right thing, I'd like to understand the sequence of operations which lead to its being needed. Can you tell me a bit more how you arrive to the tracks not being sorted ?
The thing is, I just can't remember why I added the 'sort by track number' option to the playlist popup :)

**Comment by cars10** [comment]
Yes, i mean the playlist. Sorry for the confusion.

The "workflow" for me is currently as follows:

* Start upplay
* Choose my raspberry pi where the dlna server with all my music is running
* My Yamaha AVR is already set as media renderer
* I navigate through the artists on the pi, click one, then rightclick an album and click "Send to playlist"
* *but* the songs in the playlist are not in the right order by default. I have to manually click "Sort by track number" each time i add something to the playlist .. thats where a default option would kick in. Right now it's kinda annoying to set the order each time.


Just to clarify: if i open an album manually in upplay, the songs are not in the right order either. But if i browse through the files on the pi itself or via an app on my phone (bubble upnp for example), the songs are ordered correctly. I am not sure if this is an issue with the dlna server on my pi (kodi with openelec) or if it has to do with upplay.

**Comment by medoc92** [comment]
Thanks for the details. I'll give it a try with kodi. Did you try setting the directory sorting preferences (view->preferences->Directory sorting->sort by fields) ? I am not sure that this is going to help with how the tracks are actually added, but this should take care of the directory presentation (maybe both actually, I'd have to check...)

**Comment by cars10** [comment]
Thanks for the hint (and, by the way, for the awesome support in your projects.)
I just tried that setting and it indeed takes care of the directory presentation - but the songs are still added in the wrong order to the playlist (alphabetically)

See the gif i appended.
![output](https://cloud.githubusercontent.com/assets/4118628/21944877/b7630b3a-d9d8-11e6-81b6-498a58e4f240.gif)

**Comment by medoc92** [comment]
The latest git source has a change which applies the directory custom sort criteria to lists obtained from recursive adds. This should hopefully fix your issue. I've not experimented a lot, if you can build from source, please give it a try, else it will make it's way in a future release anyway as it looks reasonable.

**Comment by cars10** [comment]
Thanks - i will try that later.

**Comment by cars10** [comment]
Totall forgot to write here - feature works great. thanks!
