### ISSUE TITLE
Cannot seek when streaming Video contents

### ISSUE THREAD

**Issue by marmz** [medoc92/upplay#60]
I know that UPplay is designed **mainly** for audio stuff, but i noticed that it can stream **almost any** file type.
In fact **videos work fine** too! 

The only problem i found is that the "seek bar" does **anything** when playing Video content to any UPnP renderer .. 
Just for completeness, using for example "GUPnP A/V Control Point" i can seek any media with no problems.
But i'd like to keep using UPplay coz it's REALLY nice and useful program with a good playlist management.

Keep on with this project, man ;)

**Comment by medoc92** [comment]
Hi,

This is probably a small issue, and I would like to fix it, even if, as you noticed, upplay is primarily for audio.
What renderer did you test with?

**Comment by medoc92** [comment]
Note for posssible future fix: the reason that seek does not work is that, at least for Kodi, there is no resource section in the DIDL fragment. Upplay normally gets the duration from there, so no duration and no seeking. There is is actually a bit of code in the OH section for renderers which do not set the duration in the metadata (get it from getpositioninfo or such), but this is not implemented for avt. So a possible solution would be: fix playlistavt.cpp to get the duration from getpositioninfo and store it somewhere as playlistohpl does (or whatever suitable equivalent will prove simpler during implementation).

**Comment by marmz** [comment]
Well, i noticed that this happens mostly when upnp server does not send info about video "duration" (length).. Intead, when this data exists, Upplay seems to seek almost fine ;)

**Comment by marmz** [comment]
@medoc92:
tested with "Kodi 17" and/or "gmediarender" on Debian 8.7.1

... Sorry for late answer :)

**Comment by medoc92** [comment]
Thanks. As noted above, I have an explanation and a solution in theory, this will be fixed in a future release...

**Comment by medoc92** [comment]
Should be fixed by this commit: 47ab37621e9795373cdc8d0f788477f6e01e8831
