### ISSUE TITLE
[Enhancement] Youtube support.

### ISSUE THREAD

**Issue by parkmino** [medoc92/upplay#66]
I'm not sure whether it is related only to upplay or upmpdcli as well.
Anyway, it would be great to support youtube.
Please refer to the followings for your information.

1) RuneAudio
http://www.runeaudio.com/forum/youtube-support-search-and-play-t647-20.html
2) Youtube-to-mpd
https://github.com/jeroendoggen/youtube-to-mpd
3) Youtube in mpd
http://devbraindom.blogspot.kr/2013/11/listen-audio-from-youtube-in-mpd.html

I could play youtube audio via command line.
$ mpc add $(youtube-dl -f bestaudio/best -g https://www.youtube.com/watch?v=G4PqySC7RR0)
$ mpc play

Thanks in advance

**Comment by medoc92** [comment]
Someone would need to program a Media Server acting as a gateway to youtube (an upmpdcli content directory plugin like the ones used for the streaming services could do this probably). The tricky part is going to be the navigation... I don't know/use youtube enough to do this.
