### ISSUE TITLE
Radio url is not listed

### ISSUE THREAD

**Issue by parkmino** [medoc92/upplay#67]
File > Select > Radio (Radio) should list internal radio urls, shoudn't it?

**Comment by medoc92** [comment]
What renderer are you using ? Assuming this is upmpdcli.

The radios listed in /etc/upmpdcli.conf, if any, should be listed in the playlist area.

https://www.lesbonscomptes.com/upmpdcli/upmpdcli-manual.html#radio-definitions

Take care that the radio definitions should be either in an external file (designated by the radiolist parameter), or at the end of the config file (because of the [xxx] section indicators).

**Comment by parkmino** [comment]
I am using upmpdcli without any midifications of radio section in /etc/upmpdcli.conf.
I do not see any radio list in playlist and wondering why?
Some radios should be added however even the default radios are not visible.

**Comment by medoc92** [comment]
I'm not sure what may be happening. Make sure that the radiolist parameter is not set if you are using the internal list (if radiolist is set, the internal list is ignored).

**Comment by parkmino** [comment]
At the moment, I am trying the internal list only.

**Comment by medoc92** [comment]
Yes, but radiolist uncommented by mistake would invalidate the internal radio list.

Otherwise, the radio list is created once, when upmdpcli start, so we need to look at the debug log during startup.

**Comment by parkmino** [comment]
'upmpdcli -d upmpd.log -l 6' as attached would be any help?
[upmpd.log.txt](https://github.com/medoc92/upplay/files/1060556/upmpd.log.txt)

**Comment by medoc92** [comment]
Yes, it helps, but it does not explain: there does not appear to be an error.

Maybe you could try to change the following lines:

                LOGDEB1("OHRadio::readRadios:RADIO: [" << title << "] uri ["
                        << uri << "] artUri [" << artUri << "]\n");

in ohradio.cxx, in function getRadiosFromConf(), around line 132

Change LOGDEB1 to LOGDEB, rebuild and restart upmpdcli, this should print all the radio data it reads from the file.

**Comment by parkmino** [comment]
Hm... I've complied it without problem for armel but this time stuch with the following error message in ubuntu 16.04 amd64.

In file included from src/avtransport.cxx:18:0:
src/avtransport.hxx:25:59: fatal error: libupnpp/device/device.hxx: No such file or directory
compilation terminated.
Makefile:814: recipe for target 'src/avtransport.o' failed

Should I download libupnpp or something?

**Comment by parkmino** [comment]
Please refer to the attached file, though I don't see any change.
[upmpd.log.txt](https://github.com/medoc92/upplay/files/1061065/upmpd.log.txt)

**Comment by medoc92** [comment]
well if you changed the log message, and we have no traces, it's not reading any radio data...

Can you share your /etc/upmpdcli.conf file ?

**Comment by parkmino** [comment]
It seems that the default upmpdcli.conf has been replaced after rebuild 
[upmpdcli.conf.txt](https://github.com/medoc92/upplay/files/1062382/upmpdcli.conf.txt)
as attached.

**Comment by medoc92** [comment]
Wow, after trying your file, I realised that you were missing a -c option on your command line. The default for upmpdcli is not to read /etc/upmpdcli.conf, but, if there is no configuration file specified, just work with default values, environment, and command line options. Please try with:

    upmpdcli -d upmpd.log.txt -l 6 -c /etc/upmpdcli.conf

**Comment by parkmino** [comment]
My bad and there's no problem on upmpdcli and upplay.
Sorry for bothering you and have a nice day!

**Comment by medoc92** [comment]
It's at least as much my fault, I should have seen it at once. Neither of us can be proud about this exchange, we should hide it somewhere :)
