### ISSUE TITLE
Playback stops at end of a track (flac only)

### ISSUE THREAD

**Issue by B-z-F** [medoc92/upplay#68]
Hi,
when playing flac files, only actual track is played (tested both with AVTransport on and off).
Playing mp3 files works fine. Also first flac file after mp3 is played.
Tested same files (minidlna as a server) and renderer with BubbleUPNP and it works fine (although no seeking possible in flac (same problem in upplay)).

**Comment by medoc92** [comment]
What renderer are you using ?

**Comment by B-z-F** [comment]
Lidl silvercrest sird 14 b1
manual: http://www.lidl-service.com/static/104645464/103087_EN.pdf

**Comment by medoc92** [comment]
Ok, I don't know how to fix this without testing on the actual renderer, and I have no way to access one.

If you are a c/c++ developper and feel like debugging this, the relevant code would probably be in:

```
upqo/avtransport_qo.h
upadapt/avtadapt.h
playlist/playlistavt.cpp
playlist/playlist.cpp
```

It also depends if the renderer supports gapless (setnextavtransporturi) or not. The code for the  avt track transitions is actually a bit hairy, and could probably be made simpler. I am not too surprised that there are bugs lurking in there.

**Comment by medoc92** [comment]
can't work on this without access to a renderer
