### ISSUE TITLE
Please add video support

### ISSUE THREAD

**Issue by kemelzaidan** [medoc92/upplay#9]
Please add video support. I know a couple of upnp/dlna media servers for linux but I don't know any active media client for those, what is very odd. I know most people use those servers to play stuff on DLNA devices such as playstation etc, but isn't it awkward that you can't watch the same  files at the server on you linux computer?

**Comment by medoc92** [comment]
Exactly what does not work with video ? As far as I can see, if the media server supports video files (e.g. minidlna does), and the renderer does too (e.g. XBMC), upplay will list video files and can tell the renderer to play them. As far as I can see, the only weirdness is that error messages are printed about finding "found object of unknown class: [object.item.videoItem]", but this does not seem to have a consequence.
